### ISSUE TITLE
[UPDATE] Depricate "UP!" reaction for messages

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [BeccaLyria/discord-documentation#521]
Feature: Reacting :up: to the message which fetches the experience points to user.
Operation: Deprecated this feature in the `13.3.1` version. More information [here](https://github.com/BeccaLyria/discord-bot/pull/667).

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Within the `docs/automatic-commands.md` file:
  - Remove `Becca will react to messages with `UP` to indicate that message generated experience points.` from the `Levelling System` line.
- There is no need to add this to the deprecated features list as this is just modification of a current feature.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.
